# Generated by Django 4.0.4 on 2022-04-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categ',
        ),
    ]
